name: master
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Check DB entries
      run: python .scripts.py

    - name: Install dependencies
      run: sudo apt-get install gettext p7zip dos2unix

    - name: Create Release Folder
      run: |
        rsync -arv --exclude='.git/' --exclude='.github/' --exclude='.gitattributes' --exclude='.gitignore' --exclude='*.py' --exclude='LICENSE' --exclude='*.md' . ./{{ secrets.RELEASE_FOLDER }}

    - name: Switch to Release Folder and Zip Folder
      run: |
        cd {{ secrets.RELEASE_FOLDER }}
        ls -la
        7z a {{ secrets.ZIP_NAME }}{{ secrets.ZIP_EXTENSION }} -p${{ secrets.ZIP_PASSWORD }} {{ secrets.RELEASE_ZIP_OPTIONS }}

    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v3
      with:
        name: icon-pack
        path: {{ secrets.RELEASE_FOLDER }}/*{{ secrets.ZIP_EXTENSION }}
        if-no-files-found: warn

    - name: Deploy pre-release
      uses: softprops/action-gh-release@v1
      if: (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main')
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        fail_on_unmatched_files: true
        files: |
          {{ secrets.RELEASE_FOLDER }}/{{ secrets.ZIP_NAME }}{{ secrets.ZIP_EXTENSION }}
        tag_name: "Latest"
        prerelease: false
